name: CI - Contact API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_ENV: test
  JWT_SECRET: test_secret
  DATABASE_URL: postgresql://test:test@localhost:5432/test

jobs:
  call-tests:
    name: Build
    uses: ./.github/workflows/tests.yml

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: call-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t orsetto-contact-api .