name: CI - Contact API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_ENV: test
  JWT_SECRET: test_secret
  DATABASE_URL: postgresql://test:test@localhost:5432/test

jobs:
  call-tests:
    name: Build
    uses: ./.github/workflows/tests.yml